### ISSUE TITLE
᲼᲼

### ISSUE THREAD

**Issue by TranCongVinh** [suegdu/PTLUP#1]
;-; Websi

**Comment by suegdu** [comment]
?

**Comment by TranCongVinh** [comment]
my discord account ;-;
has been disable

**Comment by suegdu** [comment]
new account? its not disabled but i know your funny facts but give me your new account

**Comment by TranCongVinh** [comment]
:< they said im under 13 ;--; but im 13 and they disable my account until i give them proof :)

**Comment by suegdu** [comment]
new account?

**Comment by TranCongVinh** [comment]
;-; i dont know

**Comment by TranCongVinh** [comment]
;-; why chat in github, try another app, tinder :)))???, xbox ;-;?

**Comment by suegdu** [comment]
why dont you create a discord account

if you couldnt then xbox account
